server:
  port: 8181

spring:
  application:
    name: "shop-service"
  cloud:
    consul:
      host: localhost
      port: 8500
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consul
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: create
      generate-ddl: true
      show-sql: true




      discovery:
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}

#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false