server:
  port: 8383

spring:
  application:
    name: "API-GATEWAY"
  cloud:
    consul:
      host: localhost
      port: 8500

    gateway:
      httpclient:
      routes:
        - id: Authentication service
          uri: lb://Authentication-Service
          predicates:
            - Path=/auth/**

        - id: swiggy-app
          uri: lb://SWIGGY-APP
          predicates:
            - Path=/swiggy/**
          filters:
            - name: AuthenticationFilter

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - name: AuthenticationFilter

# here filters: is required for before accessing services through api we applied security